-- Onsite Call Book — MariaDB schema
--
--   mysql -u root -p < db/schema.sql
--
-- One file for both cases. On an empty server it builds the database; on an
-- existing one it brings the schema up to date. Every statement checks for
-- itself first, so running it again does nothing the second time and it is
-- safe to run after every deployment.
--
-- Tables are created in dependency order, so the foreign keys resolve as they
-- are declared. Changes to tables that already exist are at the foot of the
-- file, under UPGRADES, because they can only run once the tables are there.
--
-- Ids are CHAR(36) and generated by the browser (crypto.randomUUID), not by
-- the database. That is deliberate: the client builds a whole change set and
-- posts it in one transaction, so it has to know the ids before the server
-- sees them.
--
-- utf8mb4 throughout: names and notes contain characters latin1 cannot hold.

CREATE DATABASE IF NOT EXISTS callbook
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE callbook;

-- ==========================================================================
-- meta
-- ==========================================================================
-- roster_version increments on every successful write. A client posts the
-- version it last saw; a mismatch means somebody else got there first and the
-- write is refused rather than silently overwriting their work.
CREATE TABLE IF NOT EXISTS meta (
  k  VARCHAR(32)  NOT NULL PRIMARY KEY,
  v  VARCHAR(190) NOT NULL DEFAULT ''
) ENGINE=InnoDB;

INSERT INTO meta (k, v) VALUES ('roster_version', '1')
  ON DUPLICATE KEY UPDATE k = k;
INSERT INTO meta (k, v) VALUES ('last_caller', '')
  ON DUPLICATE KEY UPDATE k = k;
-- The team-wide calendar subscription.
--
-- Seeded from UUID() only because SQL alone has no portable random source.
-- UUID() is version 1 - time plus the server's MAC address - so this seed is
-- guessable by somebody who knows roughly when the database was built.
-- ROTATE IT ONCE AFTER INSTALLING, from Calendar links in the app: that
-- replaces it with 128 bits from the system's own random source.
INSERT INTO meta (k, v) VALUES ('team_feed_key', REPLACE(UUID(), '-', ''))
  ON DUPLICATE KEY UPDATE k = k;
-- How long call notes are kept, in months. See bin/purge.php.
INSERT INTO meta (k, v) VALUES ('retention_months', '24')
  ON DUPLICATE KEY UPDATE k = k;

-- ==========================================================================
-- who may sign in
-- ==========================================================================
-- Accounts, not people. A `users` row is somebody who can open the app; a
-- `people` row is somebody the roster can send out or ring. Most staff are
-- only ever the second, which is why these are two tables and not one.
--
-- No row is seeded and there is deliberately no default account: the first
-- one is created once, through install.html, and that action refuses to run
-- again afterwards. What each role may do is the ROLES array in auth.php —
-- the API checks the capability, never the role name.
--
-- must_change_password is set on any password a superadmin picked, so a
-- temporary one does not stay in use and does not stay known to two people.
--
-- Sign-in is by email address. 190 rather than 254 because a utf8mb4 unique
-- index will not take more.
--
-- last_login_at is what makes a dormant account visible in the Accounts tab.
-- An account nobody has used for months is one to deactivate, and until this
-- column existed there was no way to tell one from an account in daily use.
--
-- The second factor lives in its own tables below, not in columns here: the
-- authenticator key is encrypted and the recovery codes are keyed hashes, and
-- neither belongs in a row this app reads on every single request.
CREATE TABLE IF NOT EXISTS users (
  id                   CHAR(36)     NOT NULL PRIMARY KEY,
  email                VARCHAR(190) NOT NULL,
  name                 VARCHAR(160) NOT NULL,
  role                 VARCHAR(32)  NOT NULL DEFAULT 'viewer',
  password_hash        VARCHAR(255) NOT NULL,
  must_change_password TINYINT(1)   NOT NULL DEFAULT 0,
  is_active            TINYINT(1)   NOT NULL DEFAULT 1,
  last_login_at        DATETIME     NULL,
  last_login_ip        VARCHAR(45)  NOT NULL DEFAULT '',
  created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_active (is_active)
) ENGINE=InnoDB;

-- Second sign-in factor (mfa.php). secret_enc is the TOTP key encrypted with
-- mfa_key from config.php, so reading this table alone does not reveal it.
-- last_step is the last 30-second window a code was accepted for, so the same
-- code cannot be replayed.
--
-- No row means no authenticator, which means that account enrols at its next
-- sign-in. That is the whole enrolment state: there is no "enabled" flag to
-- get out of step with whether a key actually exists.
CREATE TABLE IF NOT EXISTS mfa (
  user_id    CHAR(36)     NOT NULL PRIMARY KEY,
  secret_enc VARCHAR(255) NOT NULL,
  last_step  BIGINT       NOT NULL DEFAULT 0,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mfa_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- One-time codes for when the authenticator is lost. code_hash is a keyed
-- HMAC (mfa_key), never the code itself. used_at is stamped rather than the
-- row deleted, so "was a recovery code used, and when" has an answer.
CREATE TABLE IF NOT EXISTS mfa_recovery_codes (
  id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id   CHAR(36)     NOT NULL,
  code_hash CHAR(64)     NOT NULL,
  used_at   DATETIME     NULL,
  KEY idx_recovery_user (user_id, used_at),
  CONSTRAINT fk_recovery_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Password-reset tokens. The token itself is never stored — only its SHA-256
-- hash — so a reader of this table cannot reset anybody's password with what
-- they find in it. A row is spent by stamping used_at rather than deleting it,
-- so a link that arrives twice is refused the second time and the attempt is
-- still on record.
CREATE TABLE IF NOT EXISTS password_resets (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  user_id      CHAR(36)     NOT NULL,
  token_hash   CHAR(64)     NOT NULL,
  requested_ip VARCHAR(45)  NOT NULL DEFAULT '',
  requested_at DATETIME     NOT NULL,
  expires_at   DATETIME     NOT NULL,
  used_at      DATETIME     NULL,
  UNIQUE KEY uq_reset_token (token_hash),
  KEY idx_reset_user (user_id, used_at),
  KEY idx_reset_requested (requested_at),
  CONSTRAINT fk_reset_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Failed sign-ins, so repeated guesses can be slowed down. Rows are pruned
-- as they are counted; a successful sign-in clears that account's own.
CREATE TABLE IF NOT EXISTS login_attempts (
  id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email    VARCHAR(190) NOT NULL,
  ip       VARCHAR(45)  NOT NULL DEFAULT '',
  tried_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_attempts_email (email, tried_at),
  KEY idx_attempts_ip (ip, tried_at)
) ENGINE=InnoDB;

-- ==========================================================================
-- people, and how to reach them
-- ==========================================================================
-- feed_key authorises a calendar subscription by URL, because Outlook cannot
-- be made to send an auth header. Treat each one as a password.
--
-- role is the job title ("Field Engineer"); department is the part of the
-- business they belong to; site is where they are normally based. A duty
-- names its own site, which may differ — this is only where they usually sit.
CREATE TABLE IF NOT EXISTS people (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  name        VARCHAR(160) NOT NULL,
  role        VARCHAR(160) NOT NULL DEFAULT '',
  department  VARCHAR(160) NOT NULL DEFAULT '',
  site        VARCHAR(160) NOT NULL DEFAULT '',
  phone       VARCHAR(64)  NOT NULL DEFAULT '',
  email       VARCHAR(190) NOT NULL DEFAULT '',
  notes       TEXT         NULL,
  feed_key    CHAR(32)     NOT NULL DEFAULT '',
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_people_name (name),
  KEY idx_people_feed (feed_key)
) ENGINE=InnoDB;

-- The numbers after people.phone, in the order to try them. A chain that
-- cannot fall back to a second number stops at the first unanswered call.
CREATE TABLE IF NOT EXISTS contacts (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  person_id  CHAR(36)     NOT NULL,
  kind       VARCHAR(16)  NOT NULL DEFAULT 'mobile',
  value      VARCHAR(190) NOT NULL,
  position   INT          NOT NULL DEFAULT 0,
  KEY idx_contacts_person (person_id, position),
  CONSTRAINT fk_contacts_person FOREIGN KEY (person_id)
    REFERENCES people (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Marked unavailable. Does not remove cover on its own — it makes the app
-- say so, because deleting somebody's duty because they booked leave is how
-- a night ends up with nobody on it.
CREATE TABLE IF NOT EXISTS leave_days (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  person_id  CHAR(36)     NOT NULL,
  start_date DATE         NOT NULL,
  end_date   DATE         NOT NULL,
  reason     VARCHAR(190) NOT NULL DEFAULT '',
  KEY idx_leave_span (start_date, end_date),
  CONSTRAINT fk_leave_person FOREIGN KEY (person_id)
    REFERENCES people (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ==========================================================================
-- where they go
-- ==========================================================================
CREATE TABLE IF NOT EXISTS sites (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  name        VARCHAR(160) NOT NULL,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sites_name (name)
) ENGINE=InnoDB;

-- A repeating pattern, from which duties are generated. The duties stay real
-- rows so everything else keeps working unchanged; the rotation is only the
-- thing that writes them.
CREATE TABLE IF NOT EXISTS rotations (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  name         VARCHAR(160) NOT NULL,
  type         ENUM('standby','onsite') NOT NULL DEFAULT 'standby',
  site         VARCHAR(160) NOT NULL DEFAULT '',
  start_date   DATE         NOT NULL,
  length_days  INT          NOT NULL DEFAULT 7,
  members      TEXT         NOT NULL,          -- JSON array of person ids, in turn order
  generated_to DATE         NULL,              -- how far ahead duties already exist
  active       TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE=InnoDB;

-- A duty names its site as text rather than by id, matching the app: a site
-- can be removed without deleting cover people are relying on.
--
-- rotation_id tags duties a rotation wrote, so regenerating replaces its own
-- work and never touches a duty somebody entered by hand.
CREATE TABLE IF NOT EXISTS duties (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  person_id   CHAR(36)     NOT NULL,
  type        ENUM('standby','onsite') NOT NULL DEFAULT 'standby',
  start_date  DATE         NOT NULL,
  end_date    DATE         NOT NULL,
  site        VARCHAR(160) NOT NULL DEFAULT '',
  note        TEXT         NULL,
  rotation_id CHAR(36)     NULL,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_duties_person (person_id),
  KEY idx_duties_span (start_date, end_date),
  KEY idx_duties_rotation (rotation_id),
  CONSTRAINT fk_duties_person FOREIGN KEY (person_id)
    REFERENCES people (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- "I am covering for Thabo on Friday" without editing the duty. The duty
-- stays the record of whose rotation it is; the override says who is actually
-- reachable on those days — which is why a rotation regenerating cannot wipe
-- an arrangement somebody made.
CREATE TABLE IF NOT EXISTS overrides (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  duty_id    CHAR(36)     NOT NULL,
  person_id  CHAR(36)     NOT NULL,
  start_date DATE         NOT NULL,
  end_date   DATE         NOT NULL,
  note       VARCHAR(190) NOT NULL DEFAULT '',
  KEY idx_overrides_duty (duty_id),
  KEY idx_overrides_span (start_date, end_date),
  CONSTRAINT fk_overrides_duty FOREIGN KEY (duty_id)
    REFERENCES duties (id) ON DELETE CASCADE,
  CONSTRAINT fk_overrides_person FOREIGN KEY (person_id)
    REFERENCES people (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Who to try after the person on duty does not answer, per site. site = ''
-- is the chain used when a site has none of its own.
CREATE TABLE IF NOT EXISTS escalations (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  site          VARCHAR(160) NOT NULL DEFAULT '',
  position      INT          NOT NULL DEFAULT 0,
  person_id     CHAR(36)     NOT NULL,
  after_minutes INT          NOT NULL DEFAULT 15,
  KEY idx_esc_site (site, position),
  CONSTRAINT fk_esc_person FOREIGN KEY (person_id)
    REFERENCES people (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ==========================================================================
-- what happened
-- ==========================================================================
-- logged_at is when the row reached the server; answered_at is when the
-- outcome first became one that means somebody responded. Both are stamped by
-- PHP, never by the browser, so the time-to-answer figure survives being
-- asked where it came from.
CREATE TABLE IF NOT EXISTS calls (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  person_id   CHAR(36)     NOT NULL,
  call_date   DATE         NOT NULL,
  call_time   VARCHAR(5)   NOT NULL DEFAULT '',
  called_by   VARCHAR(160) NOT NULL DEFAULT '',
  outcome     VARCHAR(32)  NOT NULL DEFAULT '',
  note        TEXT         NULL,
  logged_at   DATETIME     NULL,
  answered_at DATETIME     NULL,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_calls_person (person_id),
  KEY idx_calls_date (call_date),
  KEY idx_calls_answered (answered_at),
  CONSTRAINT fk_calls_person FOREIGN KEY (person_id)
    REFERENCES people (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ==========================================================================
-- the handover
-- ==========================================================================
-- What the shift going off watch needs the shift coming on to know. A roster
-- says who is reachable; this says what they are walking into.
--
-- ticket_ref is free text on purpose: the ticket lives in whatever system the
-- business actually uses, and this app has no business pretending to be it.
-- It is a pointer, not a copy.
--
-- author is stamped from the session, never sent by the browser, for the same
-- reason the audit trail's `who` is: a handover nobody can be held to is
-- worth less than no handover at all. Same for every timestamp here.
--
-- A handover is not deleted. It is closed, with who closed it and when, so
-- "was this ever picked up" stays answerable after the fact.
CREATE TABLE IF NOT EXISTS handovers (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  ticket_ref      VARCHAR(64)  NOT NULL DEFAULT '',
  title           VARCHAR(190) NOT NULL,
  body            TEXT         NULL,
  priority        ENUM('low','normal','high','critical') NOT NULL DEFAULT 'normal',
  status          ENUM('open','acknowledged','closed') NOT NULL DEFAULT 'open',
  site            VARCHAR(160) NOT NULL DEFAULT '',
  -- Addressed to one person, or NULL for whoever is on next.
  for_person_id   CHAR(36)     NULL,
  author          VARCHAR(160) NOT NULL,
  author_user_id  CHAR(36)     NULL,
  created_at      DATETIME     NOT NULL,
  acknowledged_by VARCHAR(160) NULL,
  acknowledged_at DATETIME     NULL,
  closed_by       VARCHAR(160) NULL,
  closed_at       DATETIME     NULL,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_handover_status (status, priority, created_at),
  KEY idx_handover_person (for_person_id),
  KEY idx_handover_created (created_at),
  -- SET NULL, not CASCADE: removing somebody from the directory must not
  -- silently delete the handover that was addressed to them.
  CONSTRAINT fk_handover_person FOREIGN KEY (for_person_id)
    REFERENCES people (id) ON DELETE SET NULL,
  CONSTRAINT fk_handover_author FOREIGN KEY (author_user_id)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- The conversation on one handover. Append-only: there is no edit and no
-- delete, because a thread somebody can quietly rewrite is not a record of
-- what was passed on.
CREATE TABLE IF NOT EXISTS handover_notes (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  handover_id  CHAR(36)     NOT NULL,
  body         TEXT         NOT NULL,
  author       VARCHAR(160) NOT NULL,
  author_user_id CHAR(36)   NULL,
  created_at   DATETIME     NOT NULL,
  KEY idx_note_handover (handover_id, created_at),
  CONSTRAINT fk_note_handover FOREIGN KEY (handover_id)
    REFERENCES handovers (id) ON DELETE CASCADE,
  CONSTRAINT fk_note_author FOREIGN KEY (author_user_id)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- What a shift leader wants the next shift, and the managers, to know: what
-- the team got through, what is still hanging over, and what they think would
-- work better. The last of those is its own column rather than a paragraph in
-- the middle of the first, because a suggestion buried in a status update is
-- a suggestion nobody acts on.
--
-- One report per shift per site per day, so re-posting corrects rather than
-- duplicates.
CREATE TABLE IF NOT EXISTS shift_reports (
  id             CHAR(36)     NOT NULL PRIMARY KEY,
  report_date    DATE         NOT NULL,
  shift          VARCHAR(32)  NOT NULL DEFAULT 'day',
  site           VARCHAR(160) NOT NULL DEFAULT '',
  leader         VARCHAR(160) NOT NULL,
  leader_user_id CHAR(36)     NULL,
  progress       TEXT         NULL,
  watch_items    TEXT         NULL,
  optimisations  TEXT         NULL,
  created_at     DATETIME     NOT NULL,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_shift_report (report_date, shift, site),
  KEY idx_shift_date (report_date),
  CONSTRAINT fk_report_leader FOREIGN KEY (leader_user_id)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Written only by the server, inside the same transaction as the change it
-- describes. The browser cannot insert, edit or delete a row here: an audit
-- trail the client can rewrite is not one.
CREATE TABLE IF NOT EXISTS audit_log (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  logged_at   DATETIME     NOT NULL,
  who         VARCHAR(160) NOT NULL DEFAULT 'Not named',
  what        VARCHAR(500) NOT NULL,
  ip          VARCHAR(45)  NOT NULL DEFAULT '',
  KEY idx_audit_at (logged_at)
) ENGINE=InnoDB;

-- ==========================================================================
-- UPGRADES
-- ==========================================================================
-- Changes to tables that already existed. The creates above leave an existing
-- table exactly as it was, so anything that alters one has to happen here.
--
-- Each step asks information_schema whether it has already been applied and
-- does nothing if it has, which is what makes the whole file re-runnable. On
-- a database this file has just built, every one of them is a no-op.

-- --------------------------------------------------------------------------
-- Sign-in moved from a username to an email address
-- --------------------------------------------------------------------------
SET @has_username := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'username'
);

SET @sql := IF(@has_username > 0,
  'ALTER TABLE users
     DROP INDEX uq_users_username,
     CHANGE username email VARCHAR(190) NOT NULL,
     ADD UNIQUE KEY uq_users_email (email)',
  'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- The rename moves the values across as they are, and they will not be email
-- addresses. Put real ones in before anybody tries to sign in:
--
--   SELECT id, email, name, role FROM users;
--   UPDATE users SET email = 'jsmith@example.com' WHERE email = 'jsmith';

-- --------------------------------------------------------------------------
-- People gained a department and a home site
-- --------------------------------------------------------------------------
SET @has_department := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'people' AND COLUMN_NAME = 'department'
);

SET @sql := IF(@has_department = 0,
  'ALTER TABLE people
     ADD COLUMN department VARCHAR(160) NOT NULL DEFAULT "" AFTER role,
     ADD COLUMN site       VARCHAR(160) NOT NULL DEFAULT "" AFTER department',
  'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- --------------------------------------------------------------------------
-- Accounts gained a last-seen stamp
-- --------------------------------------------------------------------------
-- Existing rows keep NULL, which the Accounts tab shows as "Never". That is
-- accurate rather than missing: it is not known when they last signed in,
-- because nothing was recording it.
SET @has_last_login := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'last_login_at'
);

SET @sql := IF(@has_last_login = 0,
  'ALTER TABLE users
     ADD COLUMN last_login_at DATETIME    NULL         AFTER is_active,
     ADD COLUMN last_login_ip VARCHAR(45) NOT NULL DEFAULT "" AFTER last_login_at',
  'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- --------------------------------------------------------------------------
-- The second factor moved out of users into its own tables
-- --------------------------------------------------------------------------
-- An earlier version of this file kept the authenticator key in
-- users.totp_secret as plain base32, with an enabled flag beside it. The key
-- is now encrypted and lives in mfa, created above. These columns are dropped
-- rather than left in place, because a plaintext copy of a secret that is
-- supposed to be encrypted is worth nothing and costs everything.
--
-- Anyone who enrolled under the old scheme enrols again at their next
-- sign-in: there is no migration path from an unencrypted key to an encrypted
-- one that does not involve trusting the unencrypted one.
SET @has_old_totp := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'totp_secret'
);

SET @sql := IF(@has_old_totp > 0,
  'ALTER TABLE users
     DROP COLUMN totp_secret,
     DROP COLUMN totp_enabled,
     DROP COLUMN totp_last_counter',
  'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- The old recovery-code table went with them.
DROP TABLE IF EXISTS totp_recovery_codes;

-- ==========================================================================
-- the account the app uses
-- ==========================================================================
-- Least privilege: the app never creates or alters a table, so it is not
-- granted the right to. Change the password before running.
--
-- CREATE USER 'callbook'@'localhost' IDENTIFIED BY 'change-this-password';
-- GRANT SELECT, INSERT, UPDATE, DELETE ON callbook.* TO 'callbook'@'localhost';
-- FLUSH PRIVILEGES;
